# Generated by Django 4.1.3 on 2022-11-18 15:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='code',
            field=models.CharField(default=api.models.generates_unique_code, max_length=10, unique=True),
        ),
    ]
